export const BAD_REQUEST_ERROR = 400;
export const SERVER_ERROR = 500;
export const CREATED = 201;
export const OK = 200;
// export const NO_CONTENT = 204;
export const NOT_FOUND = 404;
export const CONFLICT_ERROR = 409;
export const UNAUTHORIZED_ERROR = 401;
export const FORBIDDEN = 403;
