const BAD_REQUEST_ERROR = 400;
const SERVER_ERROR = 500;
const CREATED = 201;
const OK = 200;
// export const NO_CONTENT = 204;
const NOT_FOUND = 404;
const CONFLICT_ERROR = 409;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN = 403;

module.exports = {
  BAD_REQUEST_ERROR,
  SERVER_ERROR,
  CREATED,
  OK,
  NOT_FOUND,
  CONFLICT_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN,
};
